/**
 * Calendário dos santos do dia.
 * - memoria/festa/solenidade/facultativa: Calendário Romano Geral (com ajustes do Brasil:
 *   Nossa Senhora Aparecida, São José de Anchieta, Santa Paulina).
 * - martirologio: nos dias sem celebração no calendário geral, um santo lembrado no
 *   Martirológio Romano nesse dia.
 */
export type TipoCelebracao = "solenidade" | "festa" | "memoria" | "facultativa" | "martirologio";

export type Celebracao = { nome: string; tipo: TipoCelebracao };

/** Chave "MM-DD". Mais de uma celebração no mesmo dia: a primeira da lista é a de maior destaque. */
export const calendarioSantos: Record<string, Celebracao[]> = {
  "01-01": [{ nome: "Santa Maria, Mãe de Deus", tipo: "solenidade" }],
  "01-02": [{ nome: "São Basílio Magno e São Gregório Nazianzeno", tipo: "memoria" }],
  "01-03": [{ nome: "Santíssimo Nome de Jesus", tipo: "facultativa" }],
  "01-04": [{ nome: "Santa Isabel Ana Bayley Seton", tipo: "martirologio" }],
  "01-05": [{ nome: "São Telésforo", tipo: "martirologio" }],
  "01-06": [{ nome: "Epifania do Senhor", tipo: "solenidade" }],
  "01-07": [{ nome: "São Raimundo de Penyafort", tipo: "facultativa" }],
  "01-08": [{ nome: "São Abo de Tiflis", tipo: "martirologio" }],
  "01-09": [{ nome: "São Adriano de Cantuária", tipo: "martirologio" }],
  "01-10": [{ nome: "Santa Léonie Aviat", tipo: "martirologio" }],
  "01-11": [{ nome: "São Higino", tipo: "martirologio" }],
  "01-12": [{ nome: "São Elredo de Rievaulx", tipo: "martirologio" }],
  "01-13": [{ nome: "Santo Hilário de Poitiers", tipo: "facultativa" }],
  "01-14": [{ nome: "São Félix de Nola", tipo: "martirologio" }],
  "01-15": [{ nome: "São Paulo, o Eremita", tipo: "martirologio" }],
  "01-16": [{ nome: "São Marcelo I", tipo: "martirologio" }],
  "01-17": [{ nome: "Santo Antão, abade", tipo: "memoria" }],
  "01-18": [{ nome: "Santa Margarida da Hungria", tipo: "martirologio" }],
  "01-19": [{ nome: "São Henrique de Uppsala", tipo: "martirologio" }],
  "01-20": [{ nome: "São Sebastião, mártir", tipo: "facultativa" }, { nome: "São Fabiano, papa e mártir", tipo: "facultativa" }],
  "01-21": [{ nome: "Santa Inês, virgem e mártir", tipo: "memoria" }],
  "01-22": [{ nome: "São Vicente, diácono e mártir", tipo: "facultativa" }],
  "01-23": [{ nome: "Santa Emerenciana", tipo: "martirologio" }],
  "01-24": [{ nome: "São Francisco de Sales", tipo: "memoria" }],
  "01-25": [{ nome: "Conversão de São Paulo", tipo: "festa" }],
  "01-26": [{ nome: "São Timóteo e São Tito", tipo: "memoria" }],
  "01-27": [{ nome: "Santa Ângela Mérici", tipo: "facultativa" }],
  "01-28": [{ nome: "São Tomás de Aquino", tipo: "memoria" }],
  "01-29": [{ nome: "São Afraates", tipo: "martirologio" }],
  "01-30": [{ nome: "Santa Batilde", tipo: "martirologio" }],
  "01-31": [{ nome: "São João Bosco", tipo: "memoria" }],
  "02-01": [{ nome: "Santa Brígida de Kildare", tipo: "martirologio" }],
  "02-02": [{ nome: "Apresentação do Senhor", tipo: "festa" }],
  "02-03": [{ nome: "São Brás, bispo e mártir", tipo: "facultativa" }, { nome: "Santo Ansgário, bispo", tipo: "facultativa" }],
  "02-04": [{ nome: "São Rábano Mauro", tipo: "martirologio" }],
  "02-05": [{ nome: "Santa Águeda, virgem e mártir", tipo: "memoria" }],
  "02-06": [{ nome: "São Paulo Miki e companheiros, mártires", tipo: "memoria" }],
  "02-07": [{ nome: "Beato Pio IX, papa", tipo: "martirologio" }],
  "02-08": [{ nome: "Santa Josefina Bakhita", tipo: "facultativa" }, { nome: "São Jerônimo Emiliani", tipo: "facultativa" }],
  "02-09": [{ nome: "Santa Apolônia, virgem e mártir", tipo: "martirologio" }],
  "02-10": [{ nome: "Santa Escolástica", tipo: "memoria" }],
  "02-11": [{ nome: "Nossa Senhora de Lourdes", tipo: "facultativa" }],
  "02-12": [{ nome: "São Bento de Aniane", tipo: "martirologio" }],
  "02-13": [{ nome: "São Ágabo, o Profeta", tipo: "martirologio" }],
  "02-14": [{ nome: "São Cirilo e São Metódio", tipo: "memoria" }],
  "02-15": [{ nome: "São Cláudio La Colombière", tipo: "martirologio" }],
  "02-16": [{ nome: "São Onésimo de Bizâncio", tipo: "martirologio" }],
  "02-17": [{ nome: "Sete Santos Fundadores da Ordem dos Servitas", tipo: "facultativa" }],
  "02-18": [{ nome: "São Simeão de Jerusalém", tipo: "martirologio" }],
  "02-19": [{ nome: "São Conrado de Placência", tipo: "martirologio" }],
  "02-20": [{ nome: "São Francisco e Santa Jacinta Marto", tipo: "martirologio" }],
  "02-21": [{ nome: "São Pedro Damião", tipo: "facultativa" }],
  "02-22": [{ nome: "Cátedra de São Pedro", tipo: "festa" }],
  "02-23": [{ nome: "São Policarpo, bispo e mártir", tipo: "memoria" }],
  "02-24": [{ nome: "São Sérgio", tipo: "martirologio" }],
  "02-25": [{ nome: "São Gerland d'Agrigente", tipo: "martirologio" }],
  "02-26": [{ nome: "São Alexandre I de Alexandria", tipo: "martirologio" }],
  "02-27": [{ nome: "São Gregório de Narek", tipo: "facultativa" }],
  "02-28": [{ nome: "São Hilário, papa", tipo: "martirologio" }],
  "02-29": [{ nome: "São Osvaldo de Worcester", tipo: "martirologio" }],
  "03-01": [{ nome: "São Albino de Angers", tipo: "martirologio" }],
  "03-02": [{ nome: "Santa Inês de Praga", tipo: "martirologio" }],
  "03-03": [{ nome: "São Marino de Cesareia", tipo: "martirologio" }],
  "03-04": [{ nome: "São Casimiro", tipo: "facultativa" }],
  "03-05": [{ nome: "São Ciarán de Saighir", tipo: "martirologio" }],
  "03-06": [{ nome: "São Fridolinho de Säckingen", tipo: "martirologio" }],
  "03-07": [{ nome: "Santa Perpétua e Santa Felicidade, mártires", tipo: "memoria" }],
  "03-08": [{ nome: "São João de Deus", tipo: "facultativa" }],
  "03-09": [{ nome: "Santa Francisca Romana", tipo: "facultativa" }],
  "03-10": [{ nome: "São Simplício", tipo: "martirologio" }],
  "03-11": [{ nome: "São Sofrônio de Jerusalém", tipo: "martirologio" }],
  "03-12": [{ nome: "São Teófanes, o Confessor", tipo: "martirologio" }],
  "03-13": [{ nome: "Santa Cristina da Pérsia, mártir", tipo: "martirologio" }],
  "03-14": [{ nome: "Santa Matilde de Ringelheim", tipo: "martirologio" }],
  "03-15": [{ nome: "São Longino", tipo: "martirologio" }],
  "03-16": [{ nome: "São Julião de Anazarbus", tipo: "martirologio" }],
  "03-17": [{ nome: "São Patrício, bispo", tipo: "facultativa" }],
  "03-18": [{ nome: "São Cirilo de Jerusalém", tipo: "facultativa" }],
  "03-19": [{ nome: "São José, esposo da Virgem Maria", tipo: "solenidade" }],
  "03-20": [{ nome: "São João Nepomuceno", tipo: "martirologio" }],
  "03-21": [{ nome: "São Bento de Núrsia", tipo: "martirologio" }],
  "03-22": [{ nome: "São Basílio de Ancira", tipo: "martirologio" }],
  "03-23": [{ nome: "São Turíbio de Mogrovejo", tipo: "facultativa" }],
  "03-24": [{ nome: "Santa Catarina da Suécia", tipo: "martirologio" }],
  "03-25": [{ nome: "Anunciação do Senhor", tipo: "solenidade" }],
  "03-26": [{ nome: "São Ludgero, bispo", tipo: "martirologio" }],
  "03-27": [{ nome: "São Ruperto de Salzburgo", tipo: "martirologio" }],
  "03-28": [{ nome: "São Sisto III", tipo: "martirologio" }],
  "03-29": [{ nome: "São Bertoldo da Calábria", tipo: "martirologio" }],
  "03-30": [{ nome: "São Quirino de Neuss", tipo: "martirologio" }],
  "03-31": [{ nome: "Santa Balbina", tipo: "martirologio" }],
  "04-01": [{ nome: "São Melito de Sardes", tipo: "martirologio" }],
  "04-02": [{ nome: "São Francisco de Paula", tipo: "facultativa" }],
  "04-03": [{ nome: "São José, o Hinógrafo", tipo: "martirologio" }],
  "04-04": [{ nome: "Santo Isidoro de Sevilha", tipo: "facultativa" }],
  "04-05": [{ nome: "São Vicente Ferrer", tipo: "facultativa" }],
  "04-06": [{ nome: "São Sisto I", tipo: "martirologio" }],
  "04-07": [{ nome: "São João Batista de La Salle", tipo: "memoria" }],
  "04-08": [{ nome: "São Dionísio de Alexandria", tipo: "martirologio" }],
  "04-09": [{ nome: "São Demétrio de Tessalônica", tipo: "martirologio" }],
  "04-10": [{ nome: "São Fulberto de Chartres", tipo: "martirologio" }],
  "04-11": [{ nome: "Santo Estanislau, bispo e mártir", tipo: "memoria" }],
  "04-12": [{ nome: "São Júlio I", tipo: "martirologio" }],
  "04-13": [{ nome: "São Martinho I, papa e mártir", tipo: "facultativa" }],
  "04-14": [{ nome: "São Bénézet d'Avignon", tipo: "martirologio" }],
  "04-15": [{ nome: "São Padarno", tipo: "martirologio" }],
  "04-16": [{ nome: "São Benedito José Labre", tipo: "martirologio" }],
  "04-17": [{ nome: "Santa Kateri Tekakwitha", tipo: "martirologio" }],
  "04-18": [{ nome: "São Galdino", tipo: "martirologio" }],
  "04-19": [{ nome: "São Expedito", tipo: "martirologio" }],
  "04-20": [{ nome: "São Beuno", tipo: "martirologio" }],
  "04-21": [{ nome: "Santo Anselmo", tipo: "facultativa" }],
  "04-22": [{ nome: "São Sotero", tipo: "martirologio" }],
  "04-23": [{ nome: "São Jorge, mártir", tipo: "facultativa" }, { nome: "Santo Adalberto, bispo e mártir", tipo: "facultativa" }],
  "04-24": [{ nome: "São Fidélis de Sigmaringa", tipo: "facultativa" }],
  "04-25": [{ nome: "São Marcos, evangelista", tipo: "festa" }],
  "04-26": [{ nome: "São Anacleto", tipo: "martirologio" }],
  "04-27": [{ nome: "Santa Zita de Lucca", tipo: "martirologio" }],
  "04-28": [{ nome: "São Pedro Chanel", tipo: "facultativa" }, { nome: "São Luís Maria Grignion de Montfort", tipo: "facultativa" }],
  "04-29": [{ nome: "Santa Catarina de Sena", tipo: "memoria" }],
  "04-30": [{ nome: "São Pio V, papa", tipo: "facultativa" }],
  "05-01": [{ nome: "São José Operário", tipo: "facultativa" }],
  "05-02": [{ nome: "Santo Atanásio", tipo: "memoria" }],
  "05-03": [{ nome: "São Filipe e São Tiago, apóstolos", tipo: "festa" }],
  "05-04": [{ nome: "São Floriano, mártir", tipo: "martirologio" }],
  "05-05": [{ nome: "São Hilário de Arles", tipo: "martirologio" }],
  "05-06": [{ nome: "São Domingos Sávio", tipo: "martirologio" }],
  "05-07": [{ nome: "São Bento II", tipo: "martirologio" }],
  "05-08": [{ nome: "São Bonifácio IV", tipo: "martirologio" }],
  "05-09": [{ nome: "São Jorge Preca", tipo: "martirologio" }],
  "05-10": [{ nome: "São João de Ávila", tipo: "martirologio" }],
  "05-11": [{ nome: "São Inácio de Laconi", tipo: "martirologio" }],
  "05-12": [{ nome: "São Nereu e São Aquiles, mártires", tipo: "facultativa" }, { nome: "São Pancrácio, mártir", tipo: "facultativa" }],
  "05-13": [{ nome: "Nossa Senhora de Fátima", tipo: "facultativa" }],
  "05-14": [{ nome: "São Matias, apóstolo", tipo: "festa" }],
  "05-15": [{ nome: "São Isidro, o Lavrador", tipo: "martirologio" }],
  "05-16": [{ nome: "São André Bobola", tipo: "martirologio" }],
  "05-17": [{ nome: "São Pascoal Bailão", tipo: "martirologio" }],
  "05-18": [{ nome: "São João I, papa e mártir", tipo: "facultativa" }],
  "05-19": [{ nome: "São Celestino V", tipo: "martirologio" }],
  "05-20": [{ nome: "São Bernardino de Sena", tipo: "facultativa" }],
  "05-21": [{ nome: "São Cristóvão Magallanes e companheiros, mártires", tipo: "facultativa" }],
  "05-22": [{ nome: "Santa Rita de Cássia", tipo: "facultativa" }],
  "05-23": [{ nome: "São João Batista de Rossi", tipo: "martirologio" }],
  "05-24": [{ nome: "São Vicente de Lérins", tipo: "martirologio" }],
  "05-25": [{ nome: "São Beda, o Venerável", tipo: "facultativa" }, { nome: "São Gregório VII, papa", tipo: "facultativa" }, { nome: "Santa Maria Madalena de Pazzi", tipo: "facultativa" }],
  "05-26": [{ nome: "São Filipe Néri", tipo: "memoria" }],
  "05-27": [{ nome: "Santo Agostinho de Cantuária", tipo: "facultativa" }],
  "05-28": [{ nome: "São Germano de Paris", tipo: "martirologio" }],
  "05-29": [{ nome: "São Paulo VI, papa", tipo: "facultativa" }],
  "05-30": [{ nome: "Santa Joana d'Arc", tipo: "martirologio" }],
  "05-31": [{ nome: "Visitação de Nossa Senhora", tipo: "festa" }],
  "06-01": [{ nome: "São Justino, mártir", tipo: "memoria" }],
  "06-02": [{ nome: "São Marcelino e São Pedro, mártires", tipo: "facultativa" }],
  "06-03": [{ nome: "São Carlos Lwanga e companheiros, mártires", tipo: "memoria" }],
  "06-04": [{ nome: "São Optato de Milevi", tipo: "martirologio" }],
  "06-05": [{ nome: "São Bonifácio, bispo e mártir", tipo: "memoria" }],
  "06-06": [{ nome: "São Norberto", tipo: "facultativa" }],
  "06-07": [{ nome: "São Mériadec de Vannes", tipo: "martirologio" }],
  "06-08": [{ nome: "São Medardo", tipo: "martirologio" }],
  "06-09": [{ nome: "São José de Anchieta", tipo: "memoria" }, { nome: "Santo Efrém", tipo: "facultativa" }],
  "06-10": [{ nome: "São Landry de Paris", tipo: "martirologio" }],
  "06-11": [{ nome: "São Barnabé, apóstolo", tipo: "memoria" }],
  "06-12": [{ nome: "Santos Basílides, Cirino, Nabor e Nazário, mártires", tipo: "martirologio" }],
  "06-13": [{ nome: "Santo Antônio de Pádua", tipo: "memoria" }],
  "06-14": [{ nome: "Beata Nhá Chica", tipo: "martirologio" }],
  "06-15": [{ nome: "Santa Germana Cousin", tipo: "martirologio" }],
  "06-16": [{ nome: "Santa Lutgarda", tipo: "martirologio" }],
  "06-17": [{ nome: "São Hervé", tipo: "martirologio" }],
  "06-18": [{ nome: "São Gregório Barbarigo", tipo: "martirologio" }],
  "06-19": [{ nome: "São Romualdo", tipo: "facultativa" }],
  "06-20": [{ nome: "São Silvério", tipo: "martirologio" }],
  "06-21": [{ nome: "São Luís Gonzaga", tipo: "memoria" }],
  "06-22": [{ nome: "São Paulino de Nola", tipo: "facultativa" }, { nome: "São João Fisher e São Tomás More", tipo: "facultativa" }],
  "06-23": [{ nome: "Santa Eteldreda de Ely", tipo: "martirologio" }],
  "06-24": [{ nome: "Natividade de São João Batista", tipo: "solenidade" }],
  "06-25": [{ nome: "São Máximo de Turim", tipo: "martirologio" }],
  "06-26": [{ nome: "São Paio de Córdova", tipo: "martirologio" }],
  "06-27": [{ nome: "São Cirilo de Alexandria", tipo: "facultativa" }],
  "06-28": [{ nome: "Santo Irineu, bispo e mártir", tipo: "memoria" }],
  "06-29": [{ nome: "São Pedro e São Paulo, apóstolos", tipo: "solenidade" }],
  "06-30": [{ nome: "Santos Primeiros Mártires da Igreja de Roma", tipo: "facultativa" }],
  "07-01": [{ nome: "São Junípero Serra", tipo: "martirologio" }],
  "07-02": [{ nome: "Santa Monegunda de Tours", tipo: "martirologio" }],
  "07-03": [{ nome: "São Tomé, apóstolo", tipo: "festa" }],
  "07-04": [{ nome: "Santa Isabel de Portugal", tipo: "facultativa" }],
  "07-05": [{ nome: "Santo Antônio Maria Zacaria", tipo: "facultativa" }],
  "07-06": [{ nome: "Santa Maria Goretti", tipo: "facultativa" }],
  "07-07": [{ nome: "Beato Pedro To Rot", tipo: "martirologio" }],
  "07-08": [{ nome: "Santa Landrada", tipo: "martirologio" }],
  "07-09": [{ nome: "Santa Paulina do Coração Agonizante de Jesus", tipo: "memoria" }, { nome: "Santo Agostinho Zhao Rong e companheiros, mártires", tipo: "facultativa" }],
  "07-10": [{ nome: "Santa Felicidade de Roma", tipo: "martirologio" }],
  "07-11": [{ nome: "São Bento, abade", tipo: "memoria" }],
  "07-12": [{ nome: "São Hermagoras de Aquileia", tipo: "martirologio" }],
  "07-13": [{ nome: "Santo Henrique", tipo: "facultativa" }],
  "07-14": [{ nome: "São Camilo de Lélis", tipo: "facultativa" }],
  "07-15": [{ nome: "São Boaventura", tipo: "memoria" }],
  "07-16": [{ nome: "Nossa Senhora do Carmo", tipo: "facultativa" }],
  "07-17": [{ nome: "São Leão IV", tipo: "martirologio" }],
  "07-18": [{ nome: "São Arnulfo de Metz", tipo: "martirologio" }],
  "07-19": [{ nome: "São Símaco", tipo: "martirologio" }],
  "07-20": [{ nome: "Santo Apolinário, bispo e mártir", tipo: "facultativa" }],
  "07-21": [{ nome: "São Lourenço de Bríndisi", tipo: "facultativa" }],
  "07-22": [{ nome: "Santa Maria Madalena", tipo: "festa" }],
  "07-23": [{ nome: "Santa Brígida", tipo: "facultativa" }],
  "07-24": [{ nome: "São Charbel Makhlouf", tipo: "facultativa" }],
  "07-25": [{ nome: "São Tiago, apóstolo", tipo: "festa" }],
  "07-26": [{ nome: "São Joaquim e Santa Ana, pais de Nossa Senhora", tipo: "memoria" }],
  "07-27": [{ nome: "São Pantaleão, mártir", tipo: "martirologio" }],
  "07-28": [{ nome: "São Vítor I", tipo: "martirologio" }],
  "07-29": [{ nome: "Santa Marta, Santa Maria e São Lázaro", tipo: "memoria" }],
  "07-30": [{ nome: "São Pedro Crisólogo", tipo: "facultativa" }],
  "07-31": [{ nome: "Santo Inácio de Loyola", tipo: "memoria" }],
  "08-01": [{ nome: "Santo Afonso Maria de Ligório", tipo: "memoria" }],
  "08-02": [{ nome: "Santo Eusébio de Vercelli", tipo: "facultativa" }, { nome: "São Pedro Julião Eymard", tipo: "facultativa" }],
  "08-03": [{ nome: "São Olavo II da Noruega", tipo: "martirologio" }],
  "08-04": [{ nome: "São João Maria Vianney", tipo: "memoria" }],
  "08-05": [{ nome: "Dedicação da Basílica de Santa Maria Maior", tipo: "facultativa" }],
  "08-06": [{ nome: "Transfiguração do Senhor", tipo: "festa" }],
  "08-07": [{ nome: "São Sisto II e companheiros, mártires", tipo: "facultativa" }, { nome: "São Caetano", tipo: "facultativa" }],
  "08-08": [{ nome: "São Domingos", tipo: "memoria" }],
  "08-09": [{ nome: "Santa Teresa Benedita da Cruz (Edith Stein)", tipo: "facultativa" }],
  "08-10": [{ nome: "São Lourenço, diácono e mártir", tipo: "festa" }],
  "08-11": [{ nome: "Santa Clara de Assis", tipo: "memoria" }],
  "08-12": [{ nome: "Santa Joana Francisca de Chantal", tipo: "facultativa" }],
  "08-13": [{ nome: "São Ponciano e São Hipólito, mártires", tipo: "facultativa" }],
  "08-14": [{ nome: "São Maximiliano Maria Kolbe", tipo: "memoria" }],
  "08-15": [{ nome: "Assunção de Nossa Senhora", tipo: "solenidade" }],
  "08-16": [{ nome: "Santo Estêvão da Hungria", tipo: "facultativa" }],
  "08-17": [{ nome: "Santa Beatriz da Silva", tipo: "martirologio" }],
  "08-18": [{ nome: "Santa Helena de Constantinopla", tipo: "martirologio" }],
  "08-19": [{ nome: "São João Eudes", tipo: "facultativa" }],
  "08-20": [{ nome: "São Bernardo de Claraval", tipo: "memoria" }],
  "08-21": [{ nome: "São Pio X, papa", tipo: "memoria" }],
  "08-22": [{ nome: "Nossa Senhora Rainha", tipo: "memoria" }],
  "08-23": [{ nome: "Santa Rosa de Lima", tipo: "facultativa" }],
  "08-24": [{ nome: "São Bartolomeu, apóstolo", tipo: "festa" }],
  "08-25": [{ nome: "São Luís, rei da França", tipo: "facultativa" }, { nome: "São José de Calasanz", tipo: "facultativa" }],
  "08-26": [{ nome: "São Alexandre de Bérgamo", tipo: "martirologio" }],
  "08-27": [{ nome: "Santa Mônica", tipo: "memoria" }],
  "08-28": [{ nome: "Santo Agostinho de Hipona", tipo: "memoria" }],
  "08-29": [{ nome: "Martírio de São João Batista", tipo: "memoria" }],
  "08-30": [{ nome: "São Friacre", tipo: "martirologio" }],
  "08-31": [{ nome: "São Aidan de Lindisfarne", tipo: "martirologio" }],
  "09-01": [{ nome: "São Egídio", tipo: "martirologio" }],
  "09-02": [{ nome: "Santa Ingrid de Skänninge", tipo: "martirologio" }],
  "09-03": [{ nome: "São Gregório Magno, papa", tipo: "memoria" }],
  "09-04": [{ nome: "Santa Rosália", tipo: "martirologio" }],
  "09-05": [{ nome: "Santa Teresa de Calcutá", tipo: "facultativa" }],
  "09-06": [{ nome: "São Magnus von Füssen", tipo: "martirologio" }],
  "09-07": [{ nome: "São Clodoaldo", tipo: "martirologio" }],
  "09-08": [{ nome: "Natividade de Nossa Senhora", tipo: "festa" }],
  "09-09": [{ nome: "São Pedro Claver", tipo: "facultativa" }],
  "09-10": [{ nome: "São Nicolau Tolentino", tipo: "martirologio" }],
  "09-11": [{ nome: "São Deiniol", tipo: "martirologio" }],
  "09-12": [{ nome: "Santíssimo Nome de Maria", tipo: "facultativa" }],
  "09-13": [{ nome: "São João Crisóstomo", tipo: "memoria" }],
  "09-14": [{ nome: "Exaltação da Santa Cruz", tipo: "festa" }],
  "09-15": [{ nome: "Nossa Senhora das Dores", tipo: "memoria" }],
  "09-16": [{ nome: "São Cornélio e São Cipriano, mártires", tipo: "memoria" }],
  "09-17": [{ nome: "São Roberto Belarmino", tipo: "facultativa" }, { nome: "Santa Hildegarda de Bingen", tipo: "facultativa" }],
  "09-18": [{ nome: "Santa Ricarda da Suábia", tipo: "martirologio" }],
  "09-19": [{ nome: "São Januário, bispo e mártir", tipo: "facultativa" }],
  "09-20": [{ nome: "Santo André Kim Taegon, São Paulo Chong Hasang e companheiros, mártires", tipo: "memoria" }],
  "09-21": [{ nome: "São Mateus, apóstolo e evangelista", tipo: "festa" }],
  "09-22": [{ nome: "São Maurício", tipo: "martirologio" }],
  "09-23": [{ nome: "São Pio de Pietrelcina (Padre Pio)", tipo: "memoria" }],
  "09-24": [{ nome: "São Gerardo Sagredo", tipo: "martirologio" }],
  "09-25": [{ nome: "São Sérgio de Radonej", tipo: "martirologio" }],
  "09-26": [{ nome: "São Cosme e São Damião, mártires", tipo: "facultativa" }],
  "09-27": [{ nome: "São Vicente de Paulo", tipo: "memoria" }],
  "09-28": [{ nome: "São Venceslau, mártir", tipo: "facultativa" }, { nome: "São Lourenço Ruiz e companheiros, mártires", tipo: "facultativa" }],
  "09-29": [{ nome: "São Miguel, São Gabriel e São Rafael, arcanjos", tipo: "festa" }],
  "09-30": [{ nome: "São Jerônimo", tipo: "memoria" }],
  "10-01": [{ nome: "Santa Teresinha do Menino Jesus", tipo: "memoria" }],
  "10-02": [{ nome: "Santos Anjos da Guarda", tipo: "memoria" }],
  "10-03": [{ nome: "Santa Théodore Guérin", tipo: "martirologio" }],
  "10-04": [{ nome: "São Francisco de Assis", tipo: "memoria" }],
  "10-05": [{ nome: "Santa Faustina Kowalska", tipo: "facultativa" }],
  "10-06": [{ nome: "São Bruno", tipo: "facultativa" }],
  "10-07": [{ nome: "Nossa Senhora do Rosário", tipo: "memoria" }],
  "10-08": [{ nome: "Santa Reparata", tipo: "martirologio" }],
  "10-09": [{ nome: "São Dionísio e companheiros, mártires", tipo: "facultativa" }, { nome: "São João Leonardi", tipo: "facultativa" }, { nome: "São João Henrique Newman", tipo: "facultativa" }],
  "10-10": [{ nome: "São Paulino de York", tipo: "martirologio" }],
  "10-11": [{ nome: "São João XXIII, papa", tipo: "facultativa" }],
  "10-12": [{ nome: "Nossa Senhora Aparecida, Padroeira do Brasil", tipo: "solenidade" }, { nome: "São Carlo Acutis", tipo: "facultativa" }],
  "10-13": [{ nome: "São Eduardo, o Confessor", tipo: "martirologio" }],
  "10-14": [{ nome: "São Calisto I, papa e mártir", tipo: "facultativa" }],
  "10-15": [{ nome: "Santa Teresa d'Ávila", tipo: "memoria" }],
  "10-16": [{ nome: "Santa Edwiges", tipo: "facultativa" }, { nome: "Santa Margarida Maria Alacoque", tipo: "facultativa" }],
  "10-17": [{ nome: "Santo Inácio de Antioquia", tipo: "memoria" }],
  "10-18": [{ nome: "São Lucas, evangelista", tipo: "festa" }],
  "10-19": [{ nome: "São João de Brébeuf, Santo Isaac Jogues e companheiros, mártires", tipo: "facultativa" }, { nome: "São Paulo da Cruz", tipo: "facultativa" }],
  "10-20": [{ nome: "Santa Bertila Boscardin", tipo: "martirologio" }],
  "10-21": [{ nome: "Santa Laura Montoya", tipo: "martirologio" }],
  "10-22": [{ nome: "São João Paulo II, papa", tipo: "facultativa" }],
  "10-23": [{ nome: "São João de Capistrano", tipo: "facultativa" }],
  "10-24": [{ nome: "Santo Antônio Maria Claret", tipo: "facultativa" }],
  "10-25": [{ nome: "São Bonifácio I", tipo: "martirologio" }],
  "10-26": [{ nome: "São Evaristo", tipo: "martirologio" }],
  "10-27": [{ nome: "São Frumêncio", tipo: "martirologio" }],
  "10-28": [{ nome: "São Simão e São Judas Tadeu, apóstolos", tipo: "festa" }],
  "10-29": [{ nome: "São Narciso de Jerusalém", tipo: "martirologio" }],
  "10-30": [{ nome: "São Serapião de Antioquia", tipo: "martirologio" }],
  "10-31": [{ nome: "São Wolfgang de Ratisbona", tipo: "martirologio" }],
  "11-01": [{ nome: "Todos os Santos", tipo: "solenidade" }],
  "11-02": [{ nome: "Comemoração de todos os fiéis defuntos", tipo: "solenidade" }],
  "11-03": [{ nome: "São Martinho de Lima (Martinho de Porres)", tipo: "facultativa" }],
  "11-04": [{ nome: "São Carlos Borromeu", tipo: "memoria" }],
  "11-05": [{ nome: "São Zacarias e Santa Isabel", tipo: "martirologio" }],
  "11-06": [{ nome: "São Leonardo de Noblac", tipo: "martirologio" }],
  "11-07": [{ nome: "São Willibrord de Utrecht", tipo: "martirologio" }],
  "11-08": [{ nome: "São Willehad", tipo: "martirologio" }],
  "11-09": [{ nome: "Dedicação da Basílica de Latrão", tipo: "festa" }],
  "11-10": [{ nome: "São Leão Magno, papa", tipo: "memoria" }],
  "11-11": [{ nome: "São Martinho de Tours", tipo: "memoria" }],
  "11-12": [{ nome: "São Josafá, bispo e mártir", tipo: "memoria" }],
  "11-13": [{ nome: "Santa Francisca Xavier Cabrini", tipo: "martirologio" }],
  "11-14": [{ nome: "São Nikola Tavelić", tipo: "martirologio" }],
  "11-15": [{ nome: "Santo Alberto Magno", tipo: "facultativa" }],
  "11-16": [{ nome: "Santa Margarida da Escócia", tipo: "facultativa" }, { nome: "Santa Gertrudes", tipo: "facultativa" }],
  "11-17": [{ nome: "Santa Isabel da Hungria", tipo: "memoria" }],
  "11-18": [{ nome: "Dedicação das Basílicas de São Pedro e São Paulo", tipo: "facultativa" }],
  "11-19": [{ nome: "Santa Matilde de Hackeborn", tipo: "martirologio" }],
  "11-20": [{ nome: "São Edmundo da Ânglia Oriental", tipo: "martirologio" }],
  "11-21": [{ nome: "Apresentação de Nossa Senhora", tipo: "memoria" }],
  "11-22": [{ nome: "Santa Cecília, virgem e mártir", tipo: "memoria" }],
  "11-23": [{ nome: "São Clemente I, papa e mártir", tipo: "facultativa" }, { nome: "São Columbano", tipo: "facultativa" }],
  "11-24": [{ nome: "Santo André Dung-Lac e companheiros, mártires", tipo: "memoria" }],
  "11-25": [{ nome: "Santa Catarina de Alexandria", tipo: "facultativa" }],
  "11-26": [{ nome: "São Sirício", tipo: "martirologio" }],
  "11-27": [{ nome: "São Virgilius van Salzburg", tipo: "martirologio" }],
  "11-28": [{ nome: "São Gregório III", tipo: "martirologio" }],
  "11-29": [{ nome: "São Saturnino de Tolosa", tipo: "martirologio" }],
  "11-30": [{ nome: "Santo André, apóstolo", tipo: "festa" }],
  "12-01": [{ nome: "São Elígio", tipo: "martirologio" }],
  "12-02": [{ nome: "São Cromácio", tipo: "martirologio" }],
  "12-03": [{ nome: "São Francisco Xavier", tipo: "memoria" }],
  "12-04": [{ nome: "São João Damasceno", tipo: "facultativa" }],
  "12-05": [{ nome: "São Sabbas, o Santificado", tipo: "martirologio" }],
  "12-06": [{ nome: "São Nicolau, bispo", tipo: "facultativa" }],
  "12-07": [{ nome: "Santo Ambrósio", tipo: "memoria" }],
  "12-08": [{ nome: "Imaculada Conceição de Nossa Senhora", tipo: "solenidade" }],
  "12-09": [{ nome: "São João Diego Cuauhtlatoatzin", tipo: "facultativa" }],
  "12-10": [{ nome: "Nossa Senhora de Loreto", tipo: "facultativa" }],
  "12-11": [{ nome: "São Dâmaso I, papa", tipo: "facultativa" }],
  "12-12": [{ nome: "Nossa Senhora de Guadalupe", tipo: "facultativa" }],
  "12-13": [{ nome: "Santa Luzia, virgem e mártir", tipo: "memoria" }],
  "12-14": [{ nome: "São João da Cruz", tipo: "memoria" }],
  "12-15": [{ nome: "Santa Virginia Centurione Bracelli", tipo: "martirologio" }],
  "12-16": [{ nome: "Santa Adelaide da Itália", tipo: "martirologio" }],
  "12-17": [{ nome: "Santa Olímpia, a Diaconisa", tipo: "martirologio" }],
  "12-18": [{ nome: "São Wunibald", tipo: "martirologio" }],
  "12-19": [{ nome: "São Anastácio I", tipo: "martirologio" }],
  "12-20": [{ nome: "São Domingos de Silos", tipo: "martirologio" }],
  "12-21": [{ nome: "São Pedro Canísio", tipo: "facultativa" }],
  "12-22": [{ nome: "Santa Francisca Xavier Cabrini", tipo: "martirologio" }],
  "12-23": [{ nome: "São João de Kety", tipo: "facultativa" }],
  "12-24": [{ nome: "Santa Paula Elisabete Cerioli", tipo: "martirologio" }],
  "12-25": [{ nome: "Natal do Senhor", tipo: "solenidade" }],
  "12-26": [{ nome: "Santo Estêvão, primeiro mártir", tipo: "festa" }],
  "12-27": [{ nome: "São João, apóstolo e evangelista", tipo: "festa" }],
  "12-28": [{ nome: "Santos Inocentes, mártires", tipo: "festa" }],
  "12-29": [{ nome: "São Tomás Becket, bispo e mártir", tipo: "facultativa" }],
  "12-30": [{ nome: "São Félix I", tipo: "martirologio" }],
  "12-31": [{ nome: "São Silvestre I, papa", tipo: "facultativa" }],
};
